from __future__ import absolute_import

# flake8: noqa

# import apis into api package
from ans_app_api.api.assignment_labels_api import AssignmentLabelsApi
from ans_app_api.api.assignments_api import AssignmentsApi
from ans_app_api.api.background_jobs_api import BackgroundJobsApi
from ans_app_api.api.blueprints_api import BlueprintsApi
from ans_app_api.api.classes_api import ClassesApi
from ans_app_api.api.comments_api import CommentsApi
from ans_app_api.api.courses_api import CoursesApi
from ans_app_api.api.courses_classes_api import CoursesClassesApi
from ans_app_api.api.courses_users_api import CoursesUsersApi
from ans_app_api.api.covers_api import CoversApi
from ans_app_api.api.departments_api import DepartmentsApi
from ans_app_api.api.domains_api import DomainsApi
from ans_app_api.api.exercises_api import ExercisesApi
from ans_app_api.api.forms_api import FormsApi
from ans_app_api.api.groups_api import GroupsApi
from ans_app_api.api.groups_users_api import GroupsUsersApi
from ans_app_api.api.insights_api import InsightsApi
from ans_app_api.api.locations_api import LocationsApi
from ans_app_api.api.logs_api import LogsApi
from ans_app_api.api.notifications_api import NotificationsApi
from ans_app_api.api.objectives_api import ObjectivesApi
from ans_app_api.api.periods_api import PeriodsApi
from ans_app_api.api.plans_api import PlansApi
from ans_app_api.api.publication_timeslots_api import PublicationTimeslotsApi
from ans_app_api.api.publications_api import PublicationsApi
from ans_app_api.api.qti_api import QtiApi
from ans_app_api.api.question_bank_assignments_api import QuestionBankAssignmentsApi
from ans_app_api.api.question_bank_exercises_api import QuestionBankExercisesApi
from ans_app_api.api.question_bank_labels_api import QuestionBankLabelsApi
from ans_app_api.api.question_banks_api import QuestionBanksApi
from ans_app_api.api.questions_api import QuestionsApi
from ans_app_api.api.requirements_api import RequirementsApi
from ans_app_api.api.result_files_api import ResultFilesApi
from ans_app_api.api.results_api import ResultsApi
from ans_app_api.api.reviews_api import ReviewsApi
from ans_app_api.api.roles_api import RolesApi
from ans_app_api.api.schools_api import SchoolsApi
from ans_app_api.api.score_marks_api import ScoreMarksApi
from ans_app_api.api.search_api import SearchApi
from ans_app_api.api.studies_api import StudiesApi
from ans_app_api.api.submissions_api import SubmissionsApi
from ans_app_api.api.subscriptions_api import SubscriptionsApi
from ans_app_api.api.tasks_api import TasksApi
from ans_app_api.api.timeslots_api import TimeslotsApi
from ans_app_api.api.users_api import UsersApi
from ans_app_api.api.webhooks_api import WebhooksApi
